// prettier-ignore
const animals = [
    "alligator", "anaconda", "angelfish", "anteater", "antelope", "ant", "apatosaurus", "atlas_beetle", "baboon", "bass", "bat", "bear", "beaver", "bee", "bison", "black_panther", "blue_whale", "boar", "boxer_dog", "buffalo", "bulldog", "bull", "butterflyfish", "butterfly", "camel", "cardinal", "catfish", "cat", "catterpillar", "centipede", "chameleon", "cheetah", "chicken", "chimera", "chimpanzee", "chinese_dragon", "chipmunk", "clam", "cobra", "cockatoo", "cockroach", "codfish", "coral", "cougar", "cow", "crab", "crocodile", "crow", "dalmatian", "deer", "doberman", "dolphin", "donkey", "dragonfly", "duck", "eagle", "earthworm", "earwig", "electric_knifefish", "elephant", "falcon", "finch", "fish", "flamingo", "flatworm", "flea", "flying_fish", "fly", "fox", "frog2", "frog", "gazelle", "german_shepherd", "gharial", "giraffe", "goat", "golden_retriever", "goldfish", "goose", "gorilla", "grasshopper", "greyhound", "griffin", "guinea_pig", "gull", "hare", "hen", "heron", "herring", "hippopotamus", "hornbill", "horse", "howling_monkey", "hummingbird", "hyena", "ibex", "iguana", "jackal", "jellyfish", "kangaroo", "killer_whale", "kingfisher", "kiwi_bird", "koala", "kraken", "ladybug", "lemur", "leopard", "lioness", "lion", "llama", "lobster", "longhorn_beetle", "lovebird", "lumpfish", "macaw", "mammoth", "manatee", "mantaray", "mantis", "meerkat", "millipede", "mite", "mole", "monkey", "moose", "mosquito", "mouse", "octopus", "ostrich", "otter", "owl", "panda", "pangolin", "parakeet", "parasaurolophus", "parrot", "peacock", "pegasus", "pelican", "penguin", "pheasant", "pigeon", "pig", "pillbug", "piranha", "platypus", "plesiosaur", "polar_bear", "prawn", "pterosaur", "pufferfish", "puffin", "python", "rabbit", "raccoon", "ram", "rat", "rattlesnake", "red_panda", "rhinoceros_beetle", "rhinoceros", "robin", "rooster", "sailfish", "salamander", "salmon", "scorpion", "sea_anemone", "seahorse", "sealion", "seal", "sea_urchin", "shark", "sheep", "sloth", "slug", "snail", "sparrow", "sperm_whale", "spider", "squid", "squirrel", "stag_beetle", "starfish", "stegosaurus", "stork", "sturgeon", "swallow", "swan", "tadpole", "tapir", "tarantula", "termite", "tiger", "toad", "tortoise", "toucan", "triceratops", "tuna", "turkey", "turtle", "tyrannosaurus", "unicorn", "vulture", "walrus", "wasp", "wild_dog", "wolf", "woodpecker", "zebra"
] as const;

export type Animal = typeof animals[keyof typeof animals];

export function getRandomAnimal() {
  return animals[Math.floor(Math.random() * animals.length)];
}
